Repository mmistakes/minimal-mistakes, pull requests merged in 2018-10, with the labels that each got.

#1864 Make entire archive/feature item "clickable"
  CHANGELOG.md
  _sass/minimal-mistakes/_archive.scss
  docs/_docs/18-history.md
Labels: Type: Enhancement

#1874 Cache "static" includes to improve build performance
  CHANGELOG.md
  _config.yml
  _includes/scripts.html
  _layouts/default.html
  docs/_config.yml
  docs/_docs/18-history.md
  minimal-mistakes-jekyll.gemspec
  test/_config.yml
Labels: Status: Accepted, Type: Enhancement

#1884 Fix Lunr search index merging words
  assets/js/lunr/lunr-store.js
Labels: Status: Accepted, Type: Bug Fix

#1885 Updated LUNR to 2.3.3
  assets/js/lunr/lunr.js
  assets/js/lunr/lunr.min.js
Labels: Status: Accepted, Type: Enhancement

#1886 Update license
  LICENSE
  LICENSE.txt
  README.md
  _layouts/default.html
  docs/_docs/04-upgrading.md
  docs/_layouts/default.html
Labels: Status: Accepted, Type: Enhancement

#1904 Fix Algolia search link positioning
  CHANGELOG.md
  _sass/minimal-mistakes/_archive.scss
  _sass/minimal-mistakes/_search.scss
  _sass/minimal-mistakes/skins/_dark.scss
  _sass/minimal-mistakes/skins/_neon.scss
  _sass/minimal-mistakes/skins/_plum.scss
  docs/_docs/18-history.md
  test/_posts/2016-02-24-welcome-to-jekyll.md
Labels: Status: Accepted, Type: Bug Fix

#1907 Revert caching for comments and analytics
  CHANGELOG.md
  _includes/scripts.html
  _layouts/default.html
Labels: Status: Accepted, Type: Bug Fix

#1888 Hindi Translation of ui-text #1887
  README.md
  _data/ui-text.yml
  docs/_pages/about.md
Labels: Status: Accepted, Type: Enhancement

#1911 New comment by Jair G
  docs/_data/comments/layout-table-of-contents-post/comment-1540422628114.yml
Labels: Type: Comment

#1915 Remove unnecessary closing bracket
  docs/_docs/05-configuration.md
Labels: Status: Accepted, Type: Bug Fix
