Repository mmistakes/minimal-mistakes, pull requests merged in 2019-02, with the labels that each got.

#2054 Remove 'www' from Stack Overflow URL
  _includes/author-profile.html
Labels: Type: Bug Fix

#2042 [fix] syntax error of non-english character
  assets/js/_main.js
Labels: Status: Accepted, Type: Bug Fix

#2053 update Font Awesome
  _includes/scripts.html
Labels: Status: Accepted, Type: Enhancement

#2056 Updated swedish translations
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2055 exit search screen with Esc key
  assets/js/_main.js
  assets/js/main.min.js
  package-lock.json
Labels: Status: Accepted, Type: Enhancement
