Repository mmistakes/minimal-mistakes, pull requests merged in 2019-10, with the labels that each got.

#2250 Allow per-page override of words_per_minute
  _includes/read-time.html
Labels: Status: Accepted, Type: Enhancement

#2251 Show a permalink anchor when hovering over headings in main content
  .gitignore
  _sass/minimal-mistakes/_page.scss
  assets/js/_main.js
  assets/js/main.min.js
Labels: Status: Accepted, Type: Enhancement

#2273 remove extraneous space from IE conditional statement
  _includes/head.html
Labels: Status: Accepted, Type: Bug Fix

#2275 Release 4.17.0
  CHANGELOG.md
  README.md
  _layouts/default.html
  _sass/minimal-mistakes.scss
  assets/js/main.min.js
  docs/_docs/01-quick-start-guide.md
  docs/_docs/04-upgrading.md
  docs/_docs/18-history.md
  docs/_layouts/default.html
  docs/_pages/home.md
  minimal-mistakes-jekyll.gemspec
  package-lock.json
  package.json
Labels: Status: Accepted, Type: Enhancement

#2276 Update the info about what js scrips you are using
  README.md
Labels: Status: Accepted, Type: Enhancement

#2285 Fix and test case
  _sass/minimal-mistakes/_utilities.scss
  test/_posts/2009-05-15-edge-case-nested-and-mixed-lists.md
Labels: Status: Accepted, Type: Enhancement

#2286 Update Chinese (Simplified) translation
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2288 Release 4.17.1 💎
  CHANGELOG.md
  README.md
  _layouts/default.html
  _sass/minimal-mistakes.scss
  assets/js/main.min.js
  docs/_docs/01-quick-start-guide.md
  docs/_docs/04-upgrading.md
  docs/_docs/18-history.md
  docs/_layouts/default.html
  docs/_pages/home.md
  minimal-mistakes-jekyll.gemspec
  package-lock.json
  package.json
Labels: Status: Accepted, Type: Enhancement

#2289 Flexbox sticky footer
  _sass/minimal-mistakes/_footer.scss
  _sass/minimal-mistakes/_page.scss
  assets/js/_main.js
  assets/js/main.min.js
Labels: Status: Accepted, Type: Bug Fix, Type: Enhancement

#2294 Added another step to the collections docs
  docs/_docs/13-collections.md
Labels: Status: Accepted, Type: Enhancement
