Repository mmistakes/minimal-mistakes, pull requests merged in 2019-03, with the labels that each got.

#2072 Add missing Chinese text strings
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2077 Add tip on how to start a YouTube embed at a given timestamp
  docs/_docs/14-helpers.md
Labels: Status: Accepted, Type: Enhancement

#2079 update Google Universal Analytics to load async
  _includes/analytics-providers/google-universal.html
Labels: Status: Accepted, Type: Enhancement

#2082 Replace jQuery Smooth Scroll with Smooth Scroll + Gumshoe
  _includes/scripts.html
  assets/js/_main.js
  assets/js/main.min.js
  assets/js/plugins/gumshoe.js
  assets/js/plugins/jquery.smooth-scroll.min.js
  assets/js/plugins/smooth-scroll.js
  package.json
  test/_posts/2016-02-24-welcome-to-jekyll.md
Labels: Status: Accepted, Type: Bug Fix, Type: Enhancement

#2094 Fix figures when they are inside of a list
  _includes/figure
Labels: Status: Accepted, Type: Bug Fix

#2096 Fix french translation typo
  _data/ui-text.yml
Labels: Status: Accepted, Type: Bug Fix

#2097 Updated vi-VN for some missing terms
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement
