Repository mmistakes/minimal-mistakes, pull requests merged in 2019-01, with the labels that each got.

#2013 Fixed Netlify typo
  docs/_docs/01-quick-start-guide.md
Labels: Status: Accepted, Type: Bug Fix

#1995 Update Font Awesome to 5.6.0
  _includes/scripts.html
Labels: Status: Accepted, Type: Enhancement

#1996 Remove unused JavaScript variables
  _includes/comments-providers/staticman.html
  _includes/comments-providers/staticman_v2.html
Labels: Status: Accepted, Type: Enhancement

#1997 [Bug fix]: Added missing Staticman Spanish UI text
  _data/ui-text.yml
Labels: Status: Accepted, Type: Bug Fix

#2004 Persian Translation of UI Elements
  README.md
  _data/ui-text.yml
  docs/_data/ui-text.yml
  docs/_docs/08-ui-text.md
  docs/_pages/about.md
Labels: Status: Accepted, Type: Enhancement

#2006 shorter IE conditional statement
  _includes/head.html
Labels: Status: Accepted, Type: Enhancement

#2010 lunr 2.3.5 update
  assets/js/lunr/lunr.js
  assets/js/lunr/lunr.min.js
Labels: Status: Accepted, Type: Enhancement

#2014 Accessibility: Add aria-label to the search button
  _data/ui-text.yml
  _includes/masthead.html
Labels: Status: Accepted, Type: Enhancement

#2019 Clicking TOC links changes hash fragment
  assets/js/_main.js
  assets/js/main.min.js
Labels: Status: Accepted, Type: Enhancement

#2020 Scrollspy-style updating of hash and TOC highlighting
  README.md
  _sass/minimal-mistakes/_navigation.scss
  _sass/minimal-mistakes/_variables.scss
  assets/js/_main.js
  assets/js/main.min.js
  assets/js/plugins/jquery.ba-throttle-debounce.js
  package.json
Labels: Status: Accepted, Type: Enhancement

#2021 Allow custom canonical url on a page-by-page basis
  _includes/seo.html
Labels: Status: Accepted, Type: Enhancement

#2022 Add support to customize `issue-term` for utterances comment provider
  _includes/comments-providers/utterances.html
Labels: Status: Accepted, Type: Enhancement

#2023 Fix scrollspy on link clicking, and # for top of page
  assets/js/_main.js
  assets/js/main.min.js
Labels: Status: Accepted, Type: Bug Fix

#2026 Add logo and title customization to the masthead
  CHANGELOG.md
  _config.yml
  _includes/masthead.html
  _sass/minimal-mistakes/_masthead.scss
  _sass/minimal-mistakes/_navigation.scss
  docs/_config.yml
  docs/_docs/05-configuration.md
  docs/_docs/18-history.md
  docs/assets/images/mm-masthead-logo.png
  test/_config.yml
  test/assets/images/apple-touch-icon.png
Labels: Status: Accepted, Type: Enhancement

#2035 Add alternate text (alt attribute) to img tag with logo
  _includes/masthead.html
Labels: Status: Accepted, Type: Bug Fix, Type: Enhancement

#2037 Add Malayalam localized UI text strings
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2043 Improve Staticman v3 documentation
  docs/_docs/05-configuration.md
Labels: Status: Accepted, Type: Enhancement
