Repository mmistakes/minimal-mistakes, pull requests merged in 2020-01, with the labels that each got.

#2355 Update toc.html from allejo/jekyll-toc:master
  _includes/toc.html
Labels: Status: Accepted, Type: Enhancement

#2359 Use %-d instead of %d for display dates
  _includes/comment.html
  _layouts/single.html
Labels: Status: Accepted, Type: Enhancement

#2364 🔧 Exclude `package-lock.json`
  _config.yml
Labels: Status: Accepted, Type: Enhancement

#2307 Allow override of page excerpt in heading (via tagline)
  _includes/page__hero.html
Labels: Status: Accepted, Type: Enhancement

#2366 Update .gitignore
  .gitignore
Labels: Status: Accepted, Type: Enhancement

#2367 Update README and LICENSE
  LICENSE
  README.md
  docs/_docs/01-quick-start-guide.md
Labels: Status: Accepted, Type: Enhancement

#2368 Fix wrong newline concatenation in SEO description
  _includes/seo.html
Labels: Type: Enhancement

#2373 Adjust comments to be compatible with compress_html
  _includes/comments-providers/disqus.html
Labels: Status: Accepted, Type: Bug Fix

#2378 Allow using theme without pagination
  _layouts/home.html
Labels: Status: Accepted, Type: Enhancement

#2381 Fix compatibility issue with paginate V2 introduced by #2378
  _layouts/home.html
Labels: Status: Accepted, Type: Bug Fix

#2385 Regression for mmistakes#2332
  CHANGELOG.md
  _includes/masthead.html
  docs/_docs/18-history.md
Labels: Status: Accepted, Type: Bug Fix
