Repository mmistakes/minimal-mistakes, pull requests merged in 2020-07, with the labels that each got.

#2583 Load Font Awesome CSS from jsDelivr CDN
  CHANGELOG.md
  _includes/head.html
  _includes/scripts.html
  docs/_docs/18-history.md
Labels: Status: Accepted, Type: Enhancement

#2558 Ignore teaser headline in table of contents
  _includes/archive-single.html
Labels: Type: Enhancement

#2570 Update 03-installation.md
  docs/_docs/03-installation.md
Labels: Status: Accepted, Type: Enhancement

#2571 Updating link to wtfpl license
  README.md
Labels: Status: Accepted, Type: Enhancement

#2572 Algolia search update
  _data/ui-text.yml
  _includes/search/algolia-search-scripts.html
Labels: Type: Enhancement

#2599 Enhance Bilibili video support (redo of #2522)
  CHANGELOG.md
  _includes/page__hero_video.html
  _includes/video
  docs/_docs/14-helpers.md
  docs/_docs/18-history.md
Labels: Type: Enhancement

#2602 Give H4 in notice some space from below
  _sass/minimal-mistakes/_notices.scss
Labels: Status: Accepted, Type: Enhancement

#2607 Fix "analytics.provider" config comment to list all analytics providers.
  _config.yml
  docs/_config.yml
  test/_config.yml
Labels: Type: Bug Fix

#2614 Change tab indent to space for consistency
  _sass/minimal-mistakes/_notices.scss
Labels: Type: Bug Fix

#2575 Add `relative_url` filter to author home link
  _includes/author-profile.html
Labels: Type: Bug Fix

#2576 Update zh-cn
  _data/ui-text.yml
Labels: Type: Enhancement

#2617 Use layout: none instead of null
  CHANGELOG.md
  assets/js/lunr/lunr-en.js
  assets/js/lunr/lunr-gr.js
  assets/js/lunr/lunr-store.js
  docs/_docs/18-history.md
Labels: Type: Bug Fix

#2616 Configure entries layout `list` or `grid`
  _layouts/home.html
  _sass/minimal-mistakes/_archive.scss
Labels: Status: Accepted, Type: Enhancement

#2626 Update UI text for zh-CN and zh-TW
  CHANGELOG.md
  _data/ui-text.yml
  docs/_docs/18-history.md
Labels: Status: Accepted, Type: Enhancement
