Repository mmistakes/minimal-mistakes, pull requests merged in 2020-11, with the labels that each got.

#2722 Update ui-text.yml for Vietnamese
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2718 Fix a small typo in documentation
  CHANGELOG.md
  docs/_docs/14-helpers.md
  docs/_docs/18-history.md
Labels: hacktoberfest-accepted

#2725 Indonesian translation
  _data/ui-text.yml
Labels: Status: Accepted, Type: Enhancement

#2713 Update jQuery to 3.5.1
  assets/js/main.min.js
  assets/js/vendor/jquery/jquery-3.5.1.js
  docs/_docs/17-javascript.md
  package-lock.json
  package.json
Labels: Status: Accepted, Type: Enhancement, hacktoberfest-accepted

#2734 Update remote theme instructions
  README.md
  docs/_docs/01-quick-start-guide.md
Labels: Status: Accepted, Type: Enhancement

#2731 Indonesian translation minor typo fix
  _data/ui-text.yml
Labels: Status: Accepted, Type: Bug Fix

#2737 Update 404.md
  docs/_pages/404.md
Labels: Status: Accepted, Type: Bug Fix
