Repository mmistakes/minimal-mistakes, pull requests merged in 2020-10, with the labels that each got.

#2697 Fix Closing Tag of Figures Without Captions in Ordered and Unordered Lists
  _includes/figure
Labels: Type: Bug Fix

#2700 Update allejo/jekyll-toc to v1.0.14
  _includes/toc.html
Labels: Type: Enhancement

#2702 Norwegian translation
  _data/ui-text.yml
  docs/_docs/08-ui-text.md
Labels: Status: Accepted, Type: Enhancement

#2674 Greedy-nav fix
  _sass/minimal-mistakes/_navigation.scss
  assets/js/main.min.js
  assets/js/plugins/jquery.greedy-navigation.js
Labels: Status: Accepted, Type: Bug Fix
