Repository mmistakes/minimal-mistakes, pull requests merged in 2020-06, with the labels that each got.

#2514 Make sticky sidebar live well with short content
  CHANGELOG.md
  _sass/minimal-mistakes/_sidebar.scss
  docs/_docs/18-history.md
Labels: Status: Feedback Needed, Type: Enhancement

#2520 Bump Jekyll version note from 3.5 to 3.7
  docs/_docs/01-quick-start-guide.md
Labels: Status: Accepted, Type: Enhancement

#2542 Strip trailing whitespace in seo_description
  _includes/seo.html
Labels: Status: Review Needed, Type: Enhancement

#2544 Move page date Liquid to include
  _includes/page__date.html
  _layouts/single.html
Labels: Status: Accepted, Type: Enhancement
