Repository mmistakes/minimal-mistakes, pull requests merged in 2020-08, with the labels that each got.

#2624 Update documentation for #2621
  CHANGELOG.md
  docs/_docs/01-quick-start-guide.md
  docs/_docs/06-overriding-theme-defaults.md
  docs/_docs/18-history.md
Labels: Status: Accepted, Type: Enhancement

#2625 Remove hidden posts from posts.html layout
  _layouts/posts.html
Labels: Status: Accepted, Type: Bug Fix

#2526 Show date of posts
  _includes/archive-single.html
  _includes/page__hero.html
  _includes/post__meta.html
  _includes/read-time.html
  _layouts/single.html
  _sass/minimal-mistakes/_page.scss
  docs/_docs/05-configuration.md
  docs/_posts/2012-01-02-layout-post-date-disabled.md
  docs/_posts/2012-01-02-layout-post-date.md
  docs/assets/images/mm-post-date-example.png
  test/_posts/2012-01-02-layout-post-date-disabled.md
  test/_posts/2012-01-02-layout-post-date.md
Labels: Status: Accepted, Type: Enhancement

#2649 Change "fa" to "fas" for Font Awesome 5
  CHANGELOG.md
  assets/js/_main.js
  assets/js/main.min.js
  docs/_docs/18-history.md
  package-lock.json
Labels: Status: Accepted, Type: Bug Fix

#2666 Removed duplicated CSS definitions
  _sass/minimal-mistakes/_footer.scss
  _sass/minimal-mistakes/_sidebar.scss
Labels: Status: Accepted, Type: Bug Fix

#2670 Added article:author used by Pinterest
  _includes/seo.html
Labels: Status: Accepted, Type: Enhancement

#2641 Refactor page meta
  _includes/archive-single.html
  _includes/page__hero.html
  _includes/page__meta.html
  _includes/post__meta.html
  _layouts/single.html
  _sass/minimal-mistakes/_archive.scss
  _sass/minimal-mistakes/_page.scss
  docs/_docs/05-configuration.md
  test/_pages/category-archive-grid.md
  test/_pages/collection-archive-grid.html
  test/_pages/collection-archive.html
  test/_pages/edge-case-grid.md
  test/_pages/markup-grid.md
  test/_pages/page-archive-grid.html
  test/_pages/page-archive.html
  test/_pages/tag-archive-grid.md
  test/_pages/year-archive-grid.md
Labels: Status: Accepted, Type: Bug Fix, Type: Enhancement
