Repository mmistakes/minimal-mistakes, pull requests merged in 2021-07, with the labels that each got.

#3024 Update README text for Gumshoejs license
  README.md
Labels: Status: Accepted, Type: Bug Fix

#3042 Remove IE9 flexbox fallback
  _includes/head.html
Labels: Status: Accepted, Type: Enhancement

#3022 Add giscus support
  CHANGELOG.md
  README.md
  _config.yml
  _includes/comments-providers/giscus.html
  _includes/comments-providers/scripts.html
  _includes/comments.html
  docs/_config.yml
  docs/_docs/05-configuration.md
  docs/_docs/18-history.md
  docs/_pages/about.md
  test/_config.yml
Labels: Status: Accepted, Type: Enhancement

#3051 Remove site.url from first breadcrumb link
  _includes/breadcrumbs.html
Labels: Status: Accepted, Type: Bug Fix

#3063 Fixed a grammar error in the german translation
  _data/ui-text.yml
Labels: Status: Accepted, Type: Bug Fix

#3064 fix: change heading tag of related posts section from `h4` to `h2` for SEO enhancement
  _layouts/single.html
  docs/_layouts/single.html
Labels: Status: Accepted, Type: Bug Fix

#3055 Add instructions on how to unminify main.js for easier browser debugging
  docs/_docs/17-javascript.md
Labels: Status: Accepted, Type: Enhancement

#3052 Add Microformats
  _includes/author-profile-custom-links.html
  _includes/author-profile.html
  _includes/category-list.html
  _includes/page__date.html
  _includes/tag-list.html
  _layouts/single.html
  _sass/minimal-mistakes/_page.scss
Labels: Status: Accepted, Type: Enhancement

#2874 Enable toc sidebar scrolling
  _sass/minimal-mistakes/_navigation.scss
  _sass/minimal-mistakes/_sidebar.scss
Labels: Status: Feedback Needed, Type: Enhancement
