Repository mmistakes/minimal-mistakes, pull requests merged in 2022-05, with the labels that each got.

#3087 Added sameAs to author links
  _includes/author-profile.html
Labels: Type: Enhancement

#3140 Use <a> color for blockquote.notice border
  _sass/minimal-mistakes/_notices.scss
Labels: Type: Enhancement

#3253 Fix inline code style not applied to stylized text
  _sass/minimal-mistakes/_base.scss
  _sass/minimal-mistakes/_page.scss
Labels: Type: Bug Fix

#3254 Update to Jquery 3.6.0
  assets/js/_main.js
  assets/js/main.min.js
  assets/js/vendor/jquery/jquery-3.6.0.js
  package-lock.json
  package.json
Labels: Type: Enhancement

#3352 add optional lunr searching of pages
  _config.yml
  assets/js/lunr/lunr-store.js
  docs/_docs/05-configuration.md
Labels: Type: Enhancement

#3489 Add Kiswahili translation
  README.md
  _data/ui-text.yml
  docs/_docs/08-ui-text.md
Labels: Type: Enhancement, Status: Accepted

#3553 Update attribution link
  assets/js/plugins/jquery.greedy-navigation.js
Labels: Status: Accepted, Type: Bug Fix

#3599 Update link to Font Awesome gallery
  docs/_docs/05-configuration.md
  docs/_docs/10-layouts.md
  docs/_docs/14-helpers.md
Labels: Type: Bug Fix

#3096 Make it possible to enable breadcrumbs per page
  _layouts/single.html
Labels: Type: Enhancement

#3102 Update algolia-search-scripts.html
  _includes/search/algolia-search-scripts.html
Labels: Status: Accepted, Type: Bug Fix

#3668 Fix #3096 enabling breadcrumb on all pages
  _layouts/single.html
Labels: Status: Accepted, Type: Bug Fix

#3666 Remove IE9 upgrade notice
  _includes/browser-upgrade.html
  _layouts/default.html
Labels: Type: Enhancement, Status: Accepted

#3669 Fix #3668 breaking "disable per-page when globally enabled"
  _layouts/single.html
Labels: Status: Accepted, Type: Bug Fix
