Repository mmistakes/minimal-mistakes, pull requests merged in 2024-05, with the labels that each got.

#2636 Add proper support for sverrirs' Jekyll Paginate V2 plugin (excl. AutoPages)
  _config.yml
  _includes/paginator-v1.html
  _includes/paginator-v2.html
  _includes/paginator.html
  docs/_docs/05-configuration.md
  docs/_docs/10-layouts.md
Labels: Type: Enhancement, Status: Accepted

#3115 Auto scroll sticky ToC with content
  assets/js/_main.js
  assets/js/main.min.js
Labels: Type: Enhancement, Status: Accepted

#4821 Remove deprecated "page.header.cta_url" setting
  _includes/page__hero.html
  docs/_docs/10-layouts.md
Labels: Type: Enhancement

#2843 Multiple Sidebar Nav Lists
  _includes/nav_list
  docs/_docs/10-layouts.md
Labels: Type: Enhancement, Status: Accepted

#3119 Feature/figure popup
  _includes/figure
  docs/_docs/14-helpers.md
Labels: Type: Enhancement, Status: Accepted

#3085 Make changes to schema easier
  _includes/schema.html
  _includes/seo.html
Labels: Type: Enhancement, Status: Review Needed

#3113 Do not markdownify title - Fixes #3094
  _includes/seo.html
  _layouts/archive.html
  _layouts/single.html
Labels: Type: Bug Fix

#2812 Copy code to clipboard
  README.md
  _config.yml
  _includes/head.html
  _sass/minimal-mistakes/_utilities.scss
  assets/js/_main.js
  assets/js/main.min.js
  docs/_config.yml
  docs/_docs/05-configuration.md
Labels: Type: Enhancement, Status: Accepted
